spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2709/bfi
    username: postgres
    password: chey

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  mail:
    host: smtp.gmail.com
    port: 587
    username: sourour.methni@gmail.com
    password: qkim dppi giko egmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true