spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bfi
    username: postgres
    password: sourour02

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: cheymabahroun@gmail.com
    password: eydj olky awnk ekgh
    properties:
      mail:
      smtp:
      auth: true
      starttls:
      enable: true